version: "3.3"

services:
  fastapi:
    build: .
    command: "python3 ./src/main.py"
    ports:
      - "${FAST_API_EXTERNAL_PORT}:${FAST_API_INTERNAL_PORT}"
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: "redis:latest"
